### PR TITLE
Fix compile error in Visual Studio

### PR DESCRIPTION
**Pull request by Sunderlandkyl**

### CODE REVIEW

**Comment by julien-l** [comment]
I am not really willing to accept this pull request because the file you modified is auto-generated by our build system so it will be overwritten during the next release...

We use the CMake function [GENERATE_EXPORT_HEADER](https://cmake.org/cmake/help/latest/module/GenerateExportHeader.html) which correctly generates the export headers for all supported platforms however we publish only one of these generated headers, and it's not the Windows one.

We will need to find a solution for that.

**Comment by Sunderlandkyl** [comment]
This is a reoccurring issue that has been fixed the same way each time:
https://github.com/clariusdev/cast/commit/22d33ec3bd3f3e7945cbd920fb71ed950bf2bb1d
https://github.com/clariusdev/cast/commit/05c61026e281bce9d7ecaa8b331d6593066c1d58
https://github.com/clariusdev/cast/commit/f21f9de7ae7740e61eb1ca0c73c43592e5b2f766

To offer a suggestion that might avoid this issue in the future, the headers could be included in the release zip files, or in separate folders in the repository for each platform.

**Comment by julien-l** [comment]
I will merge in the meantime in case it helps development.

**Comment by julien-l** [comment]
For info: the header files are now included in the zip file as suggested thanks!

**Pull request merged**
